# Generated by Django 4.1.6 on 2023-05-16 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('viewpass', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='account/default.png', null=True, upload_to='account/')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_freelancer', models.BooleanField(default=False)),
                ('is_client', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('freelancer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('about', models.TextField(default='about')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('earning', models.IntegerField(default=0)),
                ('expertise', models.CharField(default='videographer', max_length=50)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('task', models.CharField(default='videographer', max_length=200)),
                ('deadline', models.DateField()),
                ('role', models.CharField(default='videographer', max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_orders', to='account.client')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_orders', to='account.freelancer')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('link', models.CharField(default='link', max_length=100)),
                ('forclient', models.CharField(default='client', max_length=150)),
                ('role', models.CharField(default='videographer', max_length=50)),
                ('partnership', models.JSONField(blank=True, default=[], null=True)),
                ('review', models.TextField(default='description')),
                ('likes', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('is_image', models.BooleanField(default=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_portfolio', to='account.freelancer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('task', models.CharField(default='videographer', max_length=200)),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(default='pending', max_length=50)),
                ('payment_status', models.BooleanField(default=False)),
                ('role', models.CharField(default='videographer', max_length=50)),
                ('deadline', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_orders', to='account.client')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_orders', to='account.freelancer')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('task', models.CharField(default='videographer', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField()),
                ('role', models.CharField(default='videographer', max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_orders', to='account.client')),
            ],
        ),
    ]
