# Generated by Django 4.1.6 on 2023-06-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='about',
            field=models.TextField(default='about'),
        ),
    ]
