# Generated by Django 4.1.6 on 2023-06-01 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='about',
        ),
    ]
