# Generated by Django 4.1.6 on 2023-06-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_freelancer_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='username',
        ),
    ]
