# Generated by Django 4.1.6 on 2023-06-27 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_freelancer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
