# Generated by Django 4.1.6 on 2023-07-03 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_portfolio_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableprojects',
            name='applicants',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AddField(
            model_name='availableprojects',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
