# Generated by Django 4.1.6 on 2023-07-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_availableprojects_applicants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableprojects',
            name='location',
            field=models.CharField(default='remote', max_length=50),
        ),
    ]
