# Generated by Django 4.1.6 on 2023-07-09 08:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0011_delete_availableprojects'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('task', models.CharField(default='videographer', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField()),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('role', models.CharField(default='videographer', max_length=50)),
                ('applicants', models.JSONField(blank=True, default=[], null=True)),
                ('location', models.CharField(default='remote', max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_orders', to='account.client')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.freelancer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.availableprojects')),
            ],
        ),
    ]
