# Generated by Django 4.1.6 on 2023-07-09 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_delete_availableprojects'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='client',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='account.client'),
            preserve_default=False,
        ),
    ]
