# Generated by Django 4.1.6 on 2023-07-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_application_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='client',
        ),
    ]
